### PR TITLE
Ensure special characters in manifest filepaths are urlencoded

### LINKED ISSUE #33: Path encoding bug
I recently discovered that the [BagIt 1.0 specification](https://datatracker.ietf.org/doc/html/rfc8493#section-2.1.3) requires that `CR`, `LF`, and `%` in file paths within manifest files are percent-encoded, and that there isn't a single BagIt implementation that does this correctly. Implementations either **only** encode `CR` and `LF` but **not** `%` or they encode nothing.

This implementation does not encode paths in the manifest, which means that it would fail to validate BagIt 1.0 bags that include file paths containing `CR`, `LF`, or `%`. Likewise, it would create bags that would fail BagIt 1.0 validation in the case that there are paths that naturally contain percent-encoded characters.

For example, let's say a bag contains the file `data/file%0A1.txt`. This file should be written to the manifest per the spec as `data/file%250A1.txt`. However, this implementation writes it as `data/file%0A1.txt`. This means, that when this implementation validates a properly constructed 1.0 bag it will look for the file `data/file%250A1.txt` which does not exist. Similarly, if another implementation that follows the spec attempts to validate a bag produced by this implementation, it would look for `data/file\n1.txt`, which does not exist.

It would seem desirable to me to move the ecosystem in the direction of properly implementing the 1.0 specification, while at the same acknowledging that there are a large number of 1.0 bags in existence that may then become invalid.

As such, it may be prudent to, when validating bags, fall back on a series of tests. You may want to first attempt to validate per the spec, and then, if a file cannot be found, attempt to locate it by either only decoding the `CR` and `LF` or leaving the path unchanged, ideally validating all of the files using the same method.

I have not examined `fetch.txt` implementations, but the same encoding requirements exist for paths in that file as well. This is potentially a thornier problem to address in a backward compatible way as it is unclear if the path `data/file%250A1.txt` is supposed to create `data/file%250A1.txt` (incorrect) or `data/file%0A1.txt` (correct).

Finally, I created a [related ticket](https://github.com/LibraryOfCongress/bagit-spec/issues/46) against the spec discussing this encoding problem, in particular how it breaks checksum utility compatibility.

### PR DESCRIPTION
**Pull request by whikloj**
Resolves #33 

This change:
* Checks the payload manifests and fetch files of loaded Bags for any url encoded characters other than %0D, %0A and %25 and fails validation if it finds one. It also fails if it finds an unencoded newline or carriage return (though this really should never happen)
* Correctly urlencodes these characters in payload manifests and fetch files written out by this library

### CODE REVIEW

**Comment by whikloj** [comment]
@pwinckles not sure if you had a specific test that you had been running that you'd like to retry with this PR. I added some tests but always appreciate more eyes.

File: src/BagUtils.php [hunk 1]
```diff
@@ -353,4 +353,66 @@ public static function checkedFwrite($fp, $content)
...
+     * @param string $filepath
+     *   The file path to check
+     * @return bool
+     *   True if there are un-encoded characters
+     * @see \whikloj\BagItTools\BagUtils::encodeFilepath()
+     * @see \whikloj\BagItTools\BagUtils::decodeFilepath()
+     */
+    public static function checkUnencodedFilepath(string $filepath): bool
+    {
+        return (strpos($filepath, "\n") > -1 || strpos($filepath, "\r") > -1 ||
```
Comment (pwinckles) [inline src/BagUtils.php]: It's unclear to me what `fgets` considers a newline, but if you're reading the file line by line as defined by the spec where CR, LF, or CRLF are line endings, then it shouldn't be possible for the filepath to contain a CR or LF at this point.

The encoding check is technically correct. However, it does make it so the code would reject bags created by libraries that haven't be updated to encode paths correctly. I don't know if you're interested in accepting those bags or not though.

**Review by pwinckles — COMMENTED** [review]
I didn't have any specific tests. I was just eyeballing the libraries to see what they were doing.

Your changes seem good to me.

File: src/BagUtils.php (hunk 1 above)
Comment (whikloj) [reply src/BagUtils.php]: Yeah I struggled with this, mostly because I don't use PHP on Windows and so I am biased towards LF as newline characters. Looking at it now, I'm not handling CR line endings properly. I'll make a new ticket for that.

Comment (whikloj) [reply src/BagUtils.php]: #36
